.ORIG x3000

;;YOUR CODE STARTS HERE
	AND R0,R0,#0
	AND R1,R1,#0
	AND R2,R2,#0
	AND R3,R3,#0
	AND R4,R4,#0
	AND R5,R5,#0
	AND R6,R6,#0
	BRnzp START
GETCHAR ADD R0,R0,#1	
START   LEA R0,STRING_START
	LDR R6,R0,#0
	LD R1,ASCII_ZERO
	ADD R6,R6,R1
	LD R1,ASCII_NINE
	NOT R1,R1
	ADD R1,R1,#1
	ADD R1,R1,R6
	BRzp TYPEII
	OUT
	BRnzp GETCHAR
TYPEII  
	LDR R1,R0,#0
	ADD R0,R0,#1
	ST R0,FIRSTADDR
	LD R2,FIRSTADDR
ASTERISK
	AND R5,R5,#0
	LD R5,ASCII_NEG_ASTERISK
	ADD R5,R5,R6
	BRz PRINTLOOP
	LD R3,STRING_START
	ADD R3,R3,#1
	BRnzp ASTERISK
PRINTLOOP	
	ST R3,LASTADDR
	ADD R1,R1,#1
OUTERLOOP
	ADD R1,R1,#-1
	BRz GETCHAR
	LD R5,FIRSTADDR
	LD R2,FIRSTADDR
INNER	ADD R2,R2,#1
	ADD R5,R5,#1
	NOT R5,R5
	ADD R5,R5,#1
	ADD R5,R5,R3
	BRz OUTERLOOP
        LDR R2,R0,#0
	OUT
	BRnzp INNER

	

	
	



LASTADDR  .BLKW #1
FIRSTADDR .BLKW #1
ASCII_ZERO		.FILL x0030		;ASCII value of Zero
ASCII_NINE		.FILL x0039		;ASCII value of Nine
ASCII_NEG_ASTERISK   	.FILL xFFD6  		;negative of ascii value of *
ASCII_NEG_ZERO    	.FILL xFFD0		;negative of ascii value of 0
STRING_START 		.FILL x4000		;starting address of string
.END
